name: OpenLetters-Android

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Run ktlintCheck
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ktlintCheck

      - name: Run unit tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

      - name: Build debug APK
        uses: gradle/gradle-build-action@v2
        with:
          arguments: assembleDebug
